Update distroless-test.yaml

diff --git a/distroless-test.yaml b/distroless-test.yaml
--- a/distroless-test.yaml
+++ b/distroless-test.yaml
@@ -551,3 +551,179 @@ pipelines:
             - docker tag bazel/base/xray-go:xray-go chartstesting-distroless-local.jfrog.io/xray-go:${run_number}
             - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt docker-push chartstesting-distroless-local.jfrog.io/xray-go:${run_number} distroless-local --build-name="Distroless_base_image_build_xray" --build-number=${run_number} --server-id=chartstesting --url=${int_artifact_test_url} --user=${int_artifact_test_user} --password=${int_artifact_test_apikey}
             - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt bp Distroless_base_image_build_xray ${run_number} --server-id=chartstesting --url=${int_artifact_test_url} --user=${int_artifact_test_user} --password=${int_artifact_test_apikey}
+
+## Xray Scan
+
+      - name: Scan_artifactory
+        type: Bash
+        configuration:
+          affinityGroup: image1
+          inputSteps:
+            - name: Push_artifactory_sh
+          integrations:
+            - name: artifact_test
+          inputResources:
+            - name: distroless_base_internal
+            - name: distroless_base_artifactory
+        execution:
+          onExecute:
+            - source ${res_distroless_base_internal_resourcePath}/test/custom.sh
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt bs Distroless_base_image_build_artifactory ${run_number} --fail=false --server-id=chartstesting --url=${int_artifact_test_url} --user=${int_artifact_test_user} --password=${int_artifact_test_apikey} 2>&1 | tee -a artifactory-scan.log
+            - | 
+              vul_count=$(cat artifactory-scan.log | grep "\"severity\": \"High\"" | wc -l);
+              if cat artifactory-scan.log | grep -e "issues found during xray build scan" > /dev/null; then
+                  echo "Xray scan failed!"
+                  exit 1
+              fi
+          onComplete:
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt u artifactory-scan.log distroless-base-logs/${run_number}/artifactory-scan.log --server-id chartstesting --url ${int_artifact_test_url} --user ${int_artifact_test_user} --password ${int_artifact_test_apikey}
+            - popd
+          onSuccess:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "artifactory image Xray scan : Found $vul_count security issues" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/artifactory-scan.log"
+          onFailure:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "artifactory image Xray scan failed with $vul_count security issues!" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/artifactory-scan.log"
+
+      - name: Scan_distribution
+        type: Bash
+        configuration:
+          affinityGroup: image1
+          inputSteps:
+            - name: Push_distribution_sh
+          integrations:
+            - name: artifact_test
+          inputResources:
+            - name: distroless_base_internal
+            - name: distroless_base_distribution
+        execution:
+          onExecute:
+            - source ${res_distroless_base_internal_resourcePath}/test/custom.sh
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt bs Distroless_base_image_build_distribution ${run_number} --fail=false --server-id=chartstesting --url=${int_artifact_test_url} --user=${int_artifact_test_user} --password=${int_artifact_test_apikey} 2>&1 | tee -a distribution-scan.log
+            - | 
+              vul_count=$(cat distribution-scan.log | grep "\"severity\": \"High\"" | wc -l);
+              if cat distribution-scan.log | grep -e "issues found during xray build scan" > /dev/null; then
+                  echo "Xray scan failed!"
+                  exit 1
+              fi
+          onComplete:
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt u distribution-scan.log distroless-base-logs/${run_number}/distribution-scan.log --server-id chartstesting --url ${int_artifact_test_url} --user ${int_artifact_test_user} --password ${int_artifact_test_apikey}
+            - popd
+          onSuccess:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "distribution image Xray scan : Found $vul_count security issues" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/distribution-scan.log"
+          onFailure:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "distribution image Xray scan failed with $vul_count security issues!" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/distribution-scan.log"                       
+
+      - name: Scan_insight
+        type: Bash
+        configuration:
+          affinityGroup: image1
+          inputSteps:
+            - name: Push_insight_sh
+          integrations:
+            - name: artifact_test
+          inputResources:
+            - name: distroless_base_internal
+            - name: distroless_base_insight
+        execution:
+          onExecute:
+            - source ${res_distroless_base_internal_resourcePath}/test/custom.sh
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt bs Distroless_base_image_build_artifactory ${run_number} --fail=false --server-id=chartstesting --url=${int_artifact_test_url} --user=${int_artifact_test_user} --password=${int_artifact_test_apikey} 2>&1 | tee -a insight-scan.log
+            - | 
+              vul_count=$(cat insight-scan.log | grep "\"severity\": \"High\"" | wc -l);
+              if cat insight-scan.log | grep -e "issues found during xray build scan" > /dev/null; then
+                  echo "Xray scan failed!"
+                  exit 1
+              fi
+          onComplete:
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt u insight-scan.log distroless-base-logs/${run_number}/insight-scan.log --server-id chartstesting --url ${int_artifact_test_url} --user ${int_artifact_test_user} --password ${int_artifact_test_apikey}
+            - popd
+          onSuccess:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "insight image Xray scan : Found $vul_count security issues" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/insight-scan.log"
+          onFailure:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "insight image Xray scan failed with $vul_count security issues!" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/insight-scan.log"
+
+      - name: Scan_jfmc
+        type: Bash
+        configuration:
+          affinityGroup: image1
+          inputSteps:
+            - name: Push_jfmc_sh
+          integrations:
+            - name: artifact_test
+          inputResources:
+            - name: distroless_base_internal
+            - name: distroless_base_jfmc
+        execution:
+          onExecute:
+            - source ${res_distroless_base_internal_resourcePath}/test/custom.sh
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt bs Distroless_base_image_build_artifactory ${run_number} --fail=false --server-id=chartstesting --url=${int_artifact_test_url} --user=${int_artifact_test_user} --password=${int_artifact_test_apikey} 2>&1 | tee -a jfmc-scan.log
+            - | 
+              vul_count=$(cat jfmc-scan.log | grep "\"severity\": \"High\"" | wc -l);
+              if cat jfmc-scan.log | grep -e "issues found during xray build scan" > /dev/null; then
+                  echo "Xray scan failed!"
+                  exit 1
+              fi
+          onComplete:
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt u jfmc-scan.log distroless-base-logs/${run_number}/jfmc-scan.log --server-id chartstesting --url ${int_artifact_test_url} --user ${int_artifact_test_user} --password ${int_artifact_test_apikey}
+            - popd
+          onSuccess:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "jfmc image Xray scan : Found $vul_count security issues" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/jfmc-scan.log"
+          onFailure:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "jfmc image Xray scan failed with $vul_count security issues!" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/jfmc-scan.log"
+
+      - name: Scan_router
+        type: Bash
+        configuration:
+          affinityGroup: image1
+          inputSteps:
+            - name: Push_router_go
+          integrations:
+            - name: artifact_test
+          inputResources:
+            - name: distroless_base_internal
+            - name: distroless_base_router
+        execution:
+          onExecute:
+            - source ${res_distroless_base_internal_resourcePath}/test/custom.sh
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt bs Distroless_base_image_build_artifactory ${run_number} --fail=false --server-id=chartstesting --url=${int_artifact_test_url} --user=${int_artifact_test_user} --password=${int_artifact_test_apikey} 2>&1 | tee -a router-scan.log
+            - | 
+              vul_count=$(cat router-scan.log | grep "\"severity\": \"High\"" | wc -l);
+              if cat router-scan.log | grep -e "issues found during xray build scan" > /dev/null; then
+                  echo "Xray scan failed!"
+                  exit 1
+              fi
+          onComplete:
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt u router-scan.log distroless-base-logs/${run_number}/router-scan.log --server-id chartstesting --url ${int_artifact_test_url} --user ${int_artifact_test_user} --password ${int_artifact_test_apikey}
+            - popd
+          onSuccess:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "router image Xray scan : Found $vul_count security issues" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/router-scan.log"
+          onFailure:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "router image Xray scan failed with $vul_count security issues!" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/router-scan.log"
+
+      - name: Scan_xray
+        type: Bash
+        configuration:
+          affinityGroup: image1
+          inputSteps:
+            - name: Push_xray_go
+          integrations:
+            - name: artifact_test
+          inputResources:
+            - name: distroless_base_internal
+            - name: distroless_base_xray
+        execution:
+          onExecute:
+            - source ${res_distroless_base_internal_resourcePath}/test/custom.sh
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt bs Distroless_base_image_build_artifactory ${run_number} --fail=false --server-id=chartstesting --url=${int_artifact_test_url} --user=${int_artifact_test_user} --password=${int_artifact_test_apikey} 2>&1 | tee -a xray-scan.log
+            - | 
+              vul_count=$(cat xray-scan.log | grep "\"severity\": \"High\"" | wc -l);
+              if cat xray-scan.log | grep -e "issues found during xray build scan" > /dev/null; then
+                  echo "Xray scan failed!"
+                  exit 1
+              fi
+          onComplete:
+            - export JFROG_CLI_OFFER_CONFIG=false; jfrog rt u xray-scan.log distroless-base-logs/${run_number}/xray-scan.log --server-id chartstesting --url ${int_artifact_test_url} --user ${int_artifact_test_user} --password ${int_artifact_test_apikey}
+            - popd
+          onSuccess:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "xray image Xray scan : Found $vul_count security issues" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/xray-scan.log"
+          onFailure:
+            - update_commit_status_custom ${UPDATE_REPO_NAME} --context "${step_name}" --message "xray image Xray scan failed with $vul_count security issues!" --url "https://chartstesting.jfrog.io/artifactory/distroless-base-logs/${run_number}/xray-scan.log"
